In [1]:
from scipy.stats import uniform, qmc

In [3]:
sampler = qmc.LatinHypercube(d=5)
samples = sampler.random(100)

In [5]:
samples[0:10]

array([[0.85503992, 0.30167309, 0.23038877, 0.38700077, 0.23664447],
       [0.67242961, 0.08315593, 0.08703203, 0.36372671, 0.16923552],
       [0.71881604, 0.02852019, 0.94574602, 0.33847179, 0.05441092],
       [0.56372162, 0.34528787, 0.83603048, 0.7342897 , 0.00140985],
       [0.22990006, 0.85833905, 0.53293595, 0.72972368, 0.83086912],
       [0.15625606, 0.05588588, 0.55393927, 0.19451324, 0.10227412],
       [0.33705656, 0.62534397, 0.86476763, 0.07586178, 0.70380534],
       [0.69932004, 0.35398075, 0.93065311, 0.75843363, 0.77449955],
       [0.90805672, 0.68949024, 0.51507884, 0.01250978, 0.25268765],
       [0.74049104, 0.99589449, 0.09057517, 0.77544974, 0.15475174]])

In [10]:
uniform.ppf(samples[:,3], 0,1)

array([0.38700077, 0.36372671, 0.33847179, 0.7342897 , 0.72972368,
       0.19451324, 0.07586178, 0.75843363, 0.01250978, 0.77544974,
       0.04226225, 0.42840933, 0.45759329, 0.8756664 , 0.20288178,
       0.86434512, 0.34080781, 0.25060783, 0.81297377, 0.61885862,
       0.93232356, 0.94006204, 0.10294277, 0.50302352, 0.0048306 ,
       0.31390975, 0.80499899, 0.44002865, 0.49408993, 0.15480633,
       0.41395177, 0.14323627, 0.84968078, 0.16883907, 0.03462796,
       0.40127197, 0.2146645 , 0.11678512, 0.59448422, 0.9530249 ,
       0.26494792, 0.82193389, 0.39008593, 0.85037186, 0.02192495,
       0.9256272 , 0.79972565, 0.08487674, 0.63478846, 0.66444765,
       0.67534483, 0.9095001 , 0.52242055, 0.24290142, 0.2213376 ,
       0.91044385, 0.89320852, 0.8340439 , 0.98710776, 0.32828832,
       0.27237108, 0.30102946, 0.47987556, 0.46991244, 0.29633899,
       0.13975248, 0.4388704 , 0.12153332, 0.78999205, 0.28963294,
       0.99460503, 0.96136305, 0.58511879, 0.3794435 , 0.05674

In [15]:
from random import sample
import numpy as np

In [16]:
np.random.choice([1,2,3], 10)

array([1, 2, 1, 2, 2, 2, 1, 3, 1, 2])